baseURL = 'https://makwaijun.com/'
languageCode = 'en-us'
title = 'Introspections in Bytes'
theme = 'WJMinimo'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Poetry"
    url = "/poetry/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5