baseURL = 'https://makwaijun.com/'
languageCode = 'en-us'
title = 'Introspections in Bytes'
theme = 'WJMinimo'
copyright = "© 2020-2024, Wai Jun Mak"

[menu]
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    name = "Poetry"
    url = "/poetry/"
    weight = 4
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 5

[params]
  author = "Wai Jun Mak"

  [[params.social]]
    name = "Steam"
    url  = "https://steamcommunity.com/profiles/76561197988431305"
    icon = "fab fa-steam"

  [[params.social]]
    name = "Instagram"
    url  = "https://www.instagram.com/risottogeek/"
    icon = "fab fa-instagram"

  [[params.social]]
    name = "LinkedIn"
    url  = "https://www.linkedin.com/in/wai-jun-mak-1b401868?originalSubdomain=sg"
    icon = "fab fa-linkedin"

  [[params.social]]
    name = "Goodreads"
    url  = "https://www.goodreads.com/user/show/"
    icon = "fab fa-goodreads"

  blog_paginate = 10            # blog page size (used by list.html)

[Social]
linkedin = "your-linkedin-url"
steam = "your-steam-url"
goodreads = "your-goodreads-url"
instagram = "your-instagram-url"
youtube = "your-youtube-url"

paginate = 10                   # global fallback for other sections
