# filename -> list of tags (lowercase, hyphenated where multi-word)
TAG_MAP = {
"Post100.md": ["personal", "thoughts"],
"Post101.md": ["philosophy"],
"Post102.md": ["thoughts"],
"Post103.md": ["personal", "philosophy"],
"Post104.md": ["economics", "career"],
"Post105.md": ["ai"],
"Post106.md": ["career"],
"Post107.md": ["philosophy"],
"Post108.md": ["career", "philosophy"],
"Post109.md": ["career"],
"Post110.md": ["sustainability"],
"Post111.md": ["career"],
"Post112.md": ["career"],
"Post113.md": ["career"],
"Post114.md": ["economics"],
"Post115.md": ["philosophy"],
"Post116.md": ["ai", "meta"],
"Post117.md": ["meta"],
"Post118.md": ["government"],
"Post119.md": ["travel"],
"Post120.md": ["thoughts"],
"Post121.md": ["career"],
"Post122.md": ["travel"],
"Post123.md": ["travel"],
"Post124.md": ["travel"],
"Post125.md": ["philosophy"],
"Post126.md": ["meta"],
"Post127.md": ["business"],
"Post128.md": ["business"],
"Post129.md": ["business"],
"Post130.md": ["government", "current-affairs"],
"Post131.md": ["government", "current-affairs"],
"Post132.md": ["travel"],
"Post133.md": ["meta", "personal"],
"Post134.md": ["travel"],
"Post135.md": ["energy"],
"Post136.md": ["philosophy", "personal"],
"Post137.md": ["philosophy", "personal"],
"Post138.md": ["career"],
"Post139.md": ["economics"],
"Post140.md": ["philosophy"],
"Post141.md": ["career"],
"Post142.md": ["career", "travel"],
"Post29.md": ["sustainability"],
"Post30.md": ["sustainability"],
"Post31.md": ["sustainability"],
"Post32.md": ["sustainability"],
"Post33.md": ["sustainability", "economics"],
"Post34.md": ["economics"],
"Post35.md": ["economics"],
"Post36.md": ["economics"],
"Post37.md": ["economics"],
"Post38.md": ["economics"],
"Post39.md": ["economics"],
"Post40.md": ["economics"],
"Post41.md": ["thoughts"],
"Post42.md": ["economics"],
"Post43.md": ["economics"],
"Post44.md": ["economics"],
"Post45.md": ["thoughts"],
"Post46.md": ["economics"],
"Post47.md": ["economics"],
"Post48.md": ["personal"],
"Post49.md": ["education"],
"Post50.md": ["government"],
"Post51.md": ["education"],
"Post52.md": ["economics", "government"],
"Post53.md": ["sustainability", "economics"],
"Post54.md": ["sustainability", "current-affairs"],
"Post55.md": ["personal"],
"Post56.md": ["economics"],
"Post57.md": ["government"],
"Post58.md": ["economics"],
"Post66.md": ["thoughts", "philosophy"],
"Post67.md": ["thoughts"],
"Post68.md": ["personal"],
"Post69.md": ["thoughts"],
"Post70.md": ["personal"],
"Post71.md": ["personal", "relationships"],
"Post72.md": ["education"],
"Post73.md": ["education"],
"Post75.md": ["personal"],
"Post76.md": ["philosophy"],
"Post77.md": ["philosophy"],
"Post78.md": ["philosophy"],
"Post79.md": ["philosophy"],
"Post80.md": ["economics"],
"Post81.md": ["energy"],
"Post82.md": ["career"],
"Post83.md": ["personal"],
"Post84.md": ["personal"],
"Post85.md": ["decision-making"],
"Post86.md": ["decision-making"],
"Post87.md": ["sustainability"],
"Post88.md": ["decision-making"],
"Post89.md": ["decision-making"],
"Post90.md": ["personal"],
"Post91.md": ["government", "current-affairs"],
"Post92.md": ["philosophy"],
"Post93.md": ["career"],
"Post94.md": ["energy"],
"Post95.md": ["energy"],
"Post96.md": ["energy"],
"Post97.md": ["philosophy"],
"Post98.md": ["career"],
"Post99.md": ["government"],
"Post999.md": ["travel", "personal"],
"post1.md": ["thoughts", "website"],
"post10.md": ["government", "decision-making"],
"post11.md": ["thoughts"],
"post12.md": ["philosophy", "personal"],
"post13.md": ["economics"],
"post15.md": ["philosophy"],
"post2.md": ["website"],
"post26.md": ["personal"],
"post27.md": ["meta"],
"post28.md": ["sustainability"],
"post3.md": ["current-affairs", "forecast"],
"post4.md": ["thoughts"],
"post59.md": ["economics"],
"post6.md": ["thoughts"],
"post60.md": ["personal", "current-affairs"],
"post61.md": ["career"],
"post62.md": ["career"],
"post63.md": ["career"],
"post64.md": ["economics"],
"post65.md": ["economics"],
"post7.md": ["website"],
"post74.md": ["personal"],
"post8.md": ["website"],
"post9.md": ["economics", "current-affairs"],
}
